defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:lts

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run:
          name: Download dependencies (yarn)
          command: |
            yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Run tests
          command: yarn test

      # - run: yarn chromatic test --app-code=${CHROMATIC_CODE} --exit-zero-on-changes

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      # - add_ssh_keys:
      #    fingerprints:
      #      - "93:cd:3e:b6:bd:08:1c:92:01:26:38:1d:8c:bf:3e:dc"

      - run:
          name: Release
          command: yarn semantic-release || true

workflows:
  version: 2

  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
